version: '3'

services:
  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ipmanagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin